<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="pavann" name="Regression1" tests="12" failures="1" timestamp="28 Aug 2014 06:26:28 GMT" time="0.029" errors="0">
  <testcase name="Test1" time="0.007" classname="pack1.Class1"/>
  <testcase name="Test2" time="0.0" classname="pack1.Class1"/>
  <testcase name="Test7" time="0.0" classname="pack2.Class3"/>
  <testcase name="Test8" time="0.001" classname="pack2.Class3"/>
  <testcase name="Test10" time="0.0" classname="pack3.Class5"/>
  <testcase name="Test9" time="0.0" classname="pack3.Class5"/>
  <testcase name="Test3" time="0.0" classname="pack1.Class2"/>
  <testcase name="Test4" time="0.003" classname="pack1.Class2">
    <failure type="java.lang.AssertionError" message="I am fail">
      <![CDATA[java.lang.AssertionError: I am fail
	at pack1.Class2.Test4(Class2.java:13)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- Test4 -->
  <testcase name="Test5" time="0.0" classname="pack2.Class4"/>
  <testcase name="Test6" time="0.001" classname="pack2.Class4"/>
  <testcase name="Test11" time="0.0" classname="pack3.Class6"/>
  <testcase name="Test12" time="0.001" classname="pack3.Class6"/>
</testsuite> <!-- Regression1 -->
